# Generated by Django 3.0.4 on 2020-03-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0003_auto_20200329_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='protein_description',
            field=models.CharField(default='No Description', max_length=512),
        ),
    ]
