# Generated by Django 3.0.4 on 2020-03-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0006_auto_20200329_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VirusEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('effect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugstone.Effect')),
                ('virus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugstone.Virus')),
            ],
        ),
        migrations.AddField(
            model_name='virus',
            name='effects',
            field=models.ManyToManyField(through='drugstone.VirusEffect', to='drugstone.Effect'),
        ),
    ]
