# Generated by Django 3.0.4 on 2020-03-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0007_auto_20200330_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viruseffect',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='viruseffect',
            name='virus',
        ),
        migrations.AddField(
            model_name='effect',
            name='organism',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugstone.Organism'),
        ),
        migrations.DeleteModel(
            name='Virus',
        ),
        migrations.DeleteModel(
            name='VirusEffect',
        ),
    ]
