# Generated by Django 3.0.4 on 2020-03-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0008_auto_20200330_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='gene',
            field=models.CharField(default='', max_length=128),
        ),
    ]
