# Generated by Django 3.0.4 on 2020-03-31 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0009_auto_20200330_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugstone.Organism'),
        ),
    ]
