# Generated by Django 3.0.4 on 2020-04-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0010_auto_20200331_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=128)),
                ('virus', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('dataset', 'virus')},
            },
        ),
        migrations.RemoveField(
            model_name='proteingroup',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='protein_group',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='protein_group',
        ),
        migrations.AddField(
            model_name='edge',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugstone.Protein'),
        ),
        migrations.AddField(
            model_name='protein',
            name='effects',
            field=models.ManyToManyField(through='drugstone.Edge', to='drugstone.Effect'),
        ),
        migrations.DeleteModel(
            name='Organism',
        ),
        migrations.DeleteModel(
            name='ProteinGroup',
        ),
        migrations.AddField(
            model_name='effect',
            name='dataset_virus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugstone.DatasetVirus'),
        ),
    ]
