# Generated by Django 3.0.4 on 2020-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0012_auto_20200401_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='description',
            field=models.CharField(default='No description', max_length=512),
        ),
        migrations.AddField(
            model_name='protein',
            name='name',
            field=models.CharField(default='No name', max_length=128),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene',
            field=models.CharField(default='No gene', max_length=128),
        ),
        migrations.AlterField(
            model_name='protein',
            name='uniprot_code',
            field=models.CharField(default='No code', max_length=10),
        ),
    ]
