# Generated by Django 3.0.4 on 2020-04-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0014_auto_20200401_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='effect_id',
            field=models.CharField(default='No id', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='uniprot_code',
            field=models.CharField(default='No accession number', max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('effect', 'protein')},
        ),
        migrations.AlterUniqueTogether(
            name='effect',
            unique_together={('name', 'dataset_virus')},
        ),
    ]
