# Generated by Django 3.0.5 on 2020-04-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0016_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='job_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
