# Generated by Django 3.0.5 on 2020-04-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0018_task_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_protein', to='drugstone.Protein')),
                ('to_protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_protein', to='drugstone.Protein')),
            ],
            options={
                'unique_together': {('from_protein', 'to_protein')},
            },
        ),
        migrations.AddField(
            model_name='protein',
            name='proteins',
            field=models.ManyToManyField(related_name='_protein_proteins_+', through='drugstone.PPI', to='drugstone.Protein'),
        ),
    ]
