# Generated by Django 3.0.5 on 2020-04-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0018_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
