# Generated by Django 3.0.5 on 2020-04-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0021_remove_protein_proteins'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ppi',
            unique_together=set(),
        ),
    ]
