# Generated by Django 3.0.5 on 2020-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0024_auto_20200403_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pdi',
            unique_together={('protein', 'drug')},
        ),
    ]
