# Generated by Django 3.0.5 on 2020-04-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('drugstone', '0027_merge_20200404_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDI',
            new_name='ProteinDrugInteraction',
        ),
        migrations.RenameModel(
            old_name='PPI',
            new_name='ProteinProteinInteraction',
        ),
        migrations.RenameModel(
            old_name='Edge',
            new_name='ProteinViralInteraction',
        ),
        migrations.RenameModel(
            old_name='Effect',
            new_name='ViralProtein',
        ),
    ]
