# Generated by Django 3.0.5 on 2020-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0033_auto_20200407_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='description',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='name',
        ),
        migrations.RemoveField(
            model_name='proteinviralinteraction',
            name='name',
        ),
        migrations.AddField(
            model_name='proteinviralinteraction',
            name='is_AP_MS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proteinviralinteraction',
            name='is_overexpression',
            field=models.BooleanField(default=False),
        ),
    ]
