# Generated by Django 3.0.5 on 2020-04-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0035_auto_20200410_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='in_trial',
            field=models.BooleanField(default=False),
        ),
    ]
