# Generated by Django 3.0.5 on 2020-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0037_auto_20200417_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='drugs',
            field=models.ManyToManyField(related_name='interacting_drugs', through='drugstone.ProteinDrugInteraction', to='drugstone.Drug'),
        ),
    ]
