# Generated by Django 3.0.5 on 2020-05-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0038_auto_20200417_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_level', models.FloatField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstone.Protein')),
                ('tissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstone.Tissue')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='tissue_expression',
            field=models.ManyToManyField(related_name='interacting_drugs', through='drugstone.ExpressionLevel', to='drugstone.Tissue'),
        ),
    ]
