# Generated by Django 3.0.5 on 2020-05-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0041_drug_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='links',
            field=models.CharField(default='', max_length=16384),
        ),
    ]
