# Generated by Django 3.0.5 on 2021-05-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0044_auto_20210518_2145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proteindruginteraction',
            unique_together={('pdi_dataset', 'protein', 'drug')},
        ),
    ]
