# Generated by Django 3.0.5 on 2021-06-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0045_auto_20210519_1401'),
    ]

    operations = [
    ]
