# Generated by Django 3.0.5 on 2021-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0049_auto_20210616_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='entrez',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='protein',
            name='uniprot_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='protein',
            unique_together={('uniprot_code', 'gene', 'entrez')},
        ),
    ]
