# Generated by Django 3.0.5 on 2021-09-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0055_auto_20210922_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorder',
            name='icd10',
            field=models.CharField(default='', max_length=128),
        ),
    ]
