# Generated by Django 3.0.5 on 2021-09-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstone', '0056_auto_20210922_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrDiDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('link', models.CharField(default='', max_length=128)),
                ('version', models.CharField(default='', max_length=128)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DrugDisorderIndication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstone.Disorder')),
                ('drdi_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drdi_dataset_relation', to='drugstone.DrDiDataset')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstone.Drug')),
            ],
            options={
                'unique_together': {('drdi_dataset', 'drug', 'disorder')},
            },
        ),
    ]
