[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/null
logfile_maxbytes=0
childlogdir=/tmp

[program:drugstone_django]
command=gunicorn --reload --workers 1 --bind 0.0.0.0:8000 --timeout 1200 --log-level debug drugstone:application
directory=/usr/src/drugstone/
user=nobody
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:drugstone_worker]
process_name=drugstone_worker_%(process_num)02d
command=rq worker --max-jobs 1 --url redis://redis:6379/0 drugstone_tasks
directory=/usr/src/drugstone/
numprocs=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
