# Generated by Django 3.0.4 on 2020-03-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('effects', models.ManyToManyField(through='netex.Edge', to='netex.Effect')),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netex.Effect'),
        ),
        migrations.AddField(
            model_name='edge',
            name='protein_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netex.ProteinGroup'),
        ),
    ]
