# Generated by Django 3.0.4 on 2020-03-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0002_organism_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='organism',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netex.Organism'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netex.ProteinGroup'),
        ),
    ]
