# Generated by Django 3.0.4 on 2020-03-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0005_auto_20200329_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protein',
            old_name='protein_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='gene_name',
            new_name='gene',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='protein_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='proteingroup',
            name='group_id',
            field=models.IntegerField(default=-1),
        ),
    ]
