# Generated by Django 3.0.4 on 2020-04-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0011_auto_20200401_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='description',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='name',
        ),
    ]
