# Generated by Django 3.0.4 on 2020-04-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0013_auto_20200401_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='effect_id',
            field=models.CharField(default='No id', max_length=128),
        ),
        migrations.AlterField(
            model_name='effect',
            name='name',
            field=models.CharField(default='No name', max_length=128),
        ),
        migrations.AlterField(
            model_name='protein',
            name='uniprot_code',
            field=models.CharField(default='No accession number', max_length=10),
        ),
    ]
