# Generated by Django 3.0.5 on 2020-04-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0019_auto_20200403_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='proteins',
            field=models.ManyToManyField(through='netex.PPI', to='netex.Protein'),
        ),
    ]
