# Generated by Django 3.0.5 on 2020-04-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0023_auto_20200403_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='protein',
            name='proteins',
        ),
        migrations.CreateModel(
            name='PDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netex.Drug')),
                ('protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netex.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='drugs',
            field=models.ManyToManyField(through='netex.PDI', to='netex.Drug'),
        ),
    ]
