# Generated by Django 3.0.5 on 2020-04-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0019_task_status'),
        ('netex', '0026_auto_20200403_1636'),
    ]

    operations = [
    ]
