# Generated by Django 3.0.5 on 2020-04-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0028_auto_20200404_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proteinproteininteraction',
            unique_together=set(),
        ),
    ]
