# Generated by Django 3.0.5 on 2020-04-04 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0029_auto_20200405_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteindruginteraction',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netex.Drug'),
        ),
        migrations.AlterField(
            model_name='proteindruginteraction',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netex.Protein'),
        ),
        migrations.AlterField(
            model_name='proteinproteininteraction',
            name='from_protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_protein', to='netex.Protein'),
        ),
        migrations.AlterField(
            model_name='proteinproteininteraction',
            name='to_protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_protein', to='netex.Protein'),
        ),
        migrations.AlterField(
            model_name='proteinviralinteraction',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netex.ViralProtein'),
        ),
        migrations.AlterField(
            model_name='proteinviralinteraction',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netex.Protein'),
        ),
    ]
