# Generated by Django 3.0.5 on 2020-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0030_auto_20200405_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
