# Generated by Django 3.0.5 on 2020-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0031_task_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target',
            field=models.CharField(choices=[('drug', 'Drug'), ('drug-target', 'Drug Target')], default='drug-target', max_length=32),
            preserve_default=False,
        ),
    ]
