# Generated by Django 3.0.5 on 2020-04-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0032_task_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='drug',
            name='status',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='protein',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='protein',
            name='uniprot_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='viralprotein',
            name='effect_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='viralprotein',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
