# Generated by Django 3.0.5 on 2021-06-15 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0046_protein_ensembl'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsemblGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netex.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='EmsemblGeneProteinRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensembl_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netex.EnsemblGene', unique=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netex.Protein')),
            ],
            options={
                'unique_together': {('ensembl_gene', 'protein')},
            },
        ),
    ]
