# Generated by Django 3.0.5 on 2021-06-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0047_auto_20210615_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmsemblGeneProteinRelation',
        ),
    ]
