# Generated by Django 3.0.5 on 2021-06-16 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0048_delete_emsemblgeneproteinrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemblgene',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensg', to='netex.Protein'),
        ),
    ]
