# Generated by Django 3.0.5 on 2021-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netex', '0050_auto_20210722_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nodes', models.TextField(null=True)),
                ('edges', models.TextField(null=True)),
                ('config', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pdidataset',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='pdidataset',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='ppidataset',
            unique_together={('name', 'version')},
        ),
    ]
